services:
  - type: web
    name: project-one-api
    runtime: node
    plan: free
    # Change rootDir to the monorepo root instead of the server directory
    rootDir: .
    # Build only the server
    buildCommand: pnpm install && pnpm turbo build --filter=server...
    # Update start command to use the correct path
    startCommand: node apps/server/dist/main.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: FRONTEND_URL
        sync: false
      - key: DATABASE_URL
        sync: false
      # Add explicit Prisma schema path
      - key: PRISMA_SCHEMA_PATH
        value: apps/server/prisma/schema.prisma
