services:
  - type: web
    name: project-one-api
    env: node
    buildCommand: cd ../.. && pnpm install && pnpm turbo build --filter=server...
    startCommand: cd apps/server && node dist/main.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: FRONTEND_URL
        sync: false
